type ScreenConstantsType = {
  SIGN_IN_SCREEN: string;
  ON_BOARDING_SCREEN: string;
  SPALSH_SCREEN: string;
  LOGIN_SCREEN: string;
  FORGOT_PASSWORD: string;
  CHECK_MAIL_SCREEN: string;
  OTP_SCREEN: string;
  SUCCESSFULLY_RESET_SCREEN: string;
  RESET_PASSWORD_SCREEN: string;
  COMING_SOON_SCREEN: string;
  LASER_SCREEN: string;
  HOME_SCREEN: string;
  SCANNER_SCREEN: string;
  //APP ROUTES
  USER_BOTTOM_TAB: string;
  HOME_USER_SCREEN: string;
  ALERT_BOTTOM_SCREEN: string;
  CONSULTANCY_BOTTOM_SCREEN: string;
  SETTINGS_BOTTOM_SCREEN: string;
  PROFILE_BOTTOM_SCREEN: string;
  COURSE_DETAIL_SCREEN: string;
  VIDEO_COURSE_SCREEN: string;
  CHAT_SCREEN: string;
  NEW_CHAT_ROOM_SCREEN: string;
  CREATE_GROUP_CHAT: string;
  // add other screen constants as needed...
};

const ScreenConstants: ScreenConstantsType = {
  ON_BOARDING_SCREEN: 'ON_BOARDING_SCREEN',
  SPALSH_SCREEN: 'SPALSH_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGN_IN_SCREEN: 'SIGN_IN_SCREEN',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  CHECK_MAIL_SCREEN: 'CHECK_MAIL_SCREEN',
  OTP_SCREEN: 'OTP_SCREEN',
  RESET_PASSWORD_SCREEN: 'RESET_PASSWORD_SCREEN',
  SUCCESSFULLY_RESET_SCREEN: 'SUCCESSFULLY_RESET_SCREEN',
  COMING_SOON_SCREEN: 'COMING_SOON_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  LASER_SCREEN: 'LASER_SCREEN',
  SCANNER_SCREEN: 'SCANNER_SCREEN',
  USER_BOTTOM_TAB: 'USER_BOTTOM_TAB',
  HOME_USER_SCREEN: 'HOME_USER_SCREEN',
  ALERT_BOTTOM_SCREEN: 'ALERT_BOTTOM_SCREEN',
  CONSULTANCY_BOTTOM_SCREEN: 'CONSULTANCY_BOTTOM_SCREEN',
  SETTINGS_BOTTOM_SCREEN: 'SETTINGS_BOTTOM_SCREEN',
  PROFILE_BOTTOM_SCREEN: 'PROFILE_BOTTOM_SCREEN',
  COURSE_DETAIL_SCREEN: 'COURSE_DETAIL_SCREEN',
  VIDEO_COURSE_SCREEN: 'VIDEO_COURSE_SCREEN',
  CHAT_SCREEN: 'CHAT_SCREEN',
  NEW_CHAT_ROOM_SCREEN: 'NEW_CHAT_ROOM_SCREEN',
  CREATE_GROUP_CHAT: 'CREATE_GROUP_CHAT',
};

export default ScreenConstants;
