export const STORE_USER_DETAILS = 'STORE_USER_DETAILS';
export const IS_FIRST_LAUNCH = 'IS_FIRST_LAUNCH';
export const STORE_USER_TOKEN = 'STORE_USER_TOKEN';
export const LOGOUT_USER = 'LOGOUT_USER';
export const STORE_BADGE_DETAILS = 'STORE_BADGE_DETAILS';
export const STORE_BADGE_DETAILS_OFFLINE = 'STORE_BADGE_DETAILS_OFFLINE';
export const TOTAL_SCAN_COUNT = 'TOTAL_SCAN_COUNT';
export const UNSYNC_SCAN_COUNT = 'UNSYNC_SCAN_COUNT';
