export default dispatchTypes = {
  STORE_USER_DETAILS: 'STORE_USER_DETAILS',
  LOGOUT_USER: 'LOGOUT_USER',
  IS_FIRST_LAUNCH: 'IS_FIRST_LAUNCH',
  STORE_USER_TOKEN: 'STORE_USER_TOKEN',
  STORE_BADGE_DETAILS: 'STORE_BADGE_DETAILS',
  STORE_BADGE_DETAILS_OFFLINE: 'STORE_BADGE_DETAILS_OFFLINE',
  TOTAL_SCAN_COUNT: 'TOTAL_SCAN_COUNT',
  UNSYNC_SCAN_COUNT: 'UNSYNC_SCAN_COUNT',
  REQUEST_CHAT_ACCESS: 'REQUEST_CHAT_ACCESS',
  RESET_CHAT_ACCESS_REQUEST: 'RESET_CHAT_ACCESS_REQUEST',
};
